const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, '../../renderer/unico/data-collection.jsx'), 'utf8');
const statusSource = source.slice(source.indexOf('  const cpHasData ='), source.indexOf('  // Most quality indicators'));
const context = {};
vm.runInNewContext(statusSource + '\nthis.status = cpSubmissionStatus;', context);
const indicator = { id: 'falls', name: 'Patient falls' };
const submitted = { id: '1', type: 'quality', area: 'ICU', indicatorId: 'falls', month: 'Aug-26', status: 'approved', submittedAt: 1 };
const status = (rows, ind = indicator) => context.status(rows, 'ICU', ind, 'Aug-26');
assert.equal(status([submitted]), 'recorded', 'approved report is visible when collector readings are stripped');
assert.equal(status([], { ...indicator, mDen: { 'Aug-26': 138 } }), 'none', 'headcount alone is not a submitted reading');
assert.equal(status([], { ...indicator, months: { 'Aug-26': 0 } }), 'recorded', 'zero is valid data');
assert.equal(status([{ ...submitted, notObserved: true }]), 'notobs');
assert.equal(status([submitted, { ...submitted, id: '2', status: 'pending', submittedAt: 2 }]), 'pending');
assert.equal(status([{ ...submitted, area: 'ER' }]), 'none');
assert.equal(status([{ ...submitted, month: 'Jul-26' }]), 'none');
assert.equal(status([{ ...submitted, status: 'rejected' }]), 'rejected');

const dbPath = require.resolve('../db');
require.cache[dbPath] = { id: dbPath, filename: dbPath, loaded: true, exports: { getDbHandle: async () => null } };
const dc = require('../data-collection');
(async () => {
  for (let i = 0; i < 1005; i++) await dc.createSubmission({ type: 'patient', month: 'Aug-26', department: 'icu', values: { total: i } }, {});
  const first = await dc.getSubmissions({ limit: 1000 });
  const second = await dc.getSubmissions({ limit: 1000, offset: 1000 });
  assert.equal(first.length, 1000);
  assert.equal(second.length, 5);
  assert.equal(new Set([...first, ...second].map(s => s.id)).size, 1005);
  const fetchSource = source.slice(source.indexOf('  let _dcAllCache'), source.indexOf("  if (typeof window !== 'undefined') window.addEventListener('unico:data-refreshed'"));
  const urls = [];
  const fetchContext = { dcApi: { get: async url => { urls.push(url); return urls.length === 1 ? { ok: true, submissions: [], nextOffset: 1000 } : { ok: true, submissions: [{ id: 'older-visible' }], nextOffset: null }; } } };
  vm.runInNewContext(fetchSource + '\nthis.load = dcAllSubmissions;', fetchContext);
  assert.equal((await fetchContext.load())[0].id, 'older-visible', 'empty scoped page must not truncate history');
  assert.equal(urls.length, 2);
  fetchContext.dcApi.get = async () => ({ ok: false, error: 'Offline' });
  await assert.rejects(fetchContext.load(true), /Offline/, 'failed fetch must not look like empty history');
  console.log('Submission dashboard regression checks passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
